services:
  - type: web
    name: talentscore-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: talentscore
    autoDeploy: true
